export const FETCH_TOP_TRANSACTIONS_REQUEST = "TOP_TRANSACTIONS_REQUEST";
export const FETCH_TOP_TRANSACTIONS_SUCCESS = "TOP_TRANSACTIONS_SUCCESS";
export const FETCH_TOP_TRANSACTIONS_FAILURE = "TOP_TRANSACTIONS_FAILURE";
